package schema

import (
	"time"
)

type Response struct {
	Status     string      `json:"status"`
	StatusCode string      `json:"statuscode"`
	Message    string      `json:"message"`
	Result     *MapBinding `json:"result"`
}

type MapBinding struct {
	RepoUrl    string `json:"url"`
	RepoName   string `json:"name"`
	RepoHash   string `json:"hash"`
	ActorName  string `json:"actorname"`
	ActorEmail string `json:"actoremail"`
	Message    string `json:"message"`
	TagVersion string `json:"tagversion,omitempty"`
	InfraRepo  string `json:"infrarepo"`
}

type GitSchema struct {
	Action  string `json:"action"`
	Number  int    `json:"number"`
	Release struct {
		URL       string `json:"url"`
		AssetsURL string `json:"assets_url"`
		UploadURL string `json:"upload_url"`
		HTMLURL   string `json:"html_url"`
		ID        int    `json:"id"`
		Author    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"author"`
		NodeID          string        `json:"node_id"`
		TagName         string        `json:"tag_name"`
		TargetCommitish string        `json:"target_commitish"`
		Name            string        `json:"name"`
		Draft           bool          `json:"draft"`
		Prerelease      bool          `json:"prerelease"`
		CreatedAt       interface{}   `json:"created_at"`
		PublishedAt     interface{}   `json:"published_at"`
		Assets          []interface{} `json:"assets"`
		TarballURL      string        `json:"tarball_url"`
		ZipballURL      string        `json:"zipball_url"`
		Body            string        `json:"body"`
	} `json:"release"`

	PullRequest struct {
		URL      string `json:"url"`
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		HTMLURL  string `json:"html_url"`
		DiffURL  string `json:"diff_url"`
		PatchURL string `json:"patch_url"`
		IssueURL string `json:"issue_url"`
		Number   int    `json:"number"`
		State    string `json:"state"`
		Locked   bool   `json:"locked"`
		Title    string `json:"title"`
		User     struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"user"`
		Body               string        `json:"body"`
		CreatedAt          interface{}   `json:"created_at"`
		UpdatedAt          interface{}   `json:"updated_at"`
		ClosedAt           interface{}   `json:"closed_at"`
		MergedAt           interface{}   `json:"merged_at"`
		MergeCommitSha     string        `json:"merge_commit_sha"`
		Assignee           interface{}   `json:"assignee"`
		Assignees          []interface{} `json:"assignees"`
		RequestedReviewers []interface{} `json:"requested_reviewers"`
		RequestedTeams     []interface{} `json:"requested_teams"`
		Labels             []interface{} `json:"labels"`
		Milestone          interface{}   `json:"milestone"`
		Draft              bool          `json:"draft"`
		CommitsURL         string        `json:"commits_url"`
		ReviewCommentsURL  string        `json:"review_comments_url"`
		ReviewCommentURL   string        `json:"review_comment_url"`
		CommentsURL        string        `json:"comments_url"`
		StatusesURL        string        `json:"statuses_url"`
		Head               struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Repo struct {
				ID       int    `json:"id"`
				NodeID   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Private  bool   `json:"private"`
				Owner    struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				HTMLURL                   string        `json:"html_url"`
				Description               string        `json:"description"`
				Fork                      bool          `json:"fork"`
				URL                       string        `json:"url"`
				ForksURL                  string        `json:"forks_url"`
				KeysURL                   string        `json:"keys_url"`
				CollaboratorsURL          string        `json:"collaborators_url"`
				TeamsURL                  string        `json:"teams_url"`
				HooksURL                  string        `json:"hooks_url"`
				IssueEventsURL            string        `json:"issue_events_url"`
				EventsURL                 string        `json:"events_url"`
				AssigneesURL              string        `json:"assignees_url"`
				BranchesURL               string        `json:"branches_url"`
				TagsURL                   string        `json:"tags_url"`
				BlobsURL                  string        `json:"blobs_url"`
				GitTagsURL                string        `json:"git_tags_url"`
				GitRefsURL                string        `json:"git_refs_url"`
				TreesURL                  string        `json:"trees_url"`
				StatusesURL               string        `json:"statuses_url"`
				LanguagesURL              string        `json:"languages_url"`
				StargazersURL             string        `json:"stargazers_url"`
				ContributorsURL           string        `json:"contributors_url"`
				SubscribersURL            string        `json:"subscribers_url"`
				SubscriptionURL           string        `json:"subscription_url"`
				CommitsURL                string        `json:"commits_url"`
				GitCommitsURL             string        `json:"git_commits_url"`
				CommentsURL               string        `json:"comments_url"`
				IssueCommentURL           string        `json:"issue_comment_url"`
				ContentsURL               string        `json:"contents_url"`
				CompareURL                string        `json:"compare_url"`
				MergesURL                 string        `json:"merges_url"`
				ArchiveURL                string        `json:"archive_url"`
				DownloadsURL              string        `json:"downloads_url"`
				IssuesURL                 string        `json:"issues_url"`
				PullsURL                  string        `json:"pulls_url"`
				MilestonesURL             string        `json:"milestones_url"`
				NotificationsURL          string        `json:"notifications_url"`
				LabelsURL                 string        `json:"labels_url"`
				ReleasesURL               string        `json:"releases_url"`
				DeploymentsURL            string        `json:"deployments_url"`
				CreatedAt                 interface{}   `json:"created_at"`
				UpdatedAt                 interface{}   `json:"updated_at"`
				PushedAt                  interface{}   `json:"pushed_at"`
				GitURL                    string        `json:"git_url"`
				SSHURL                    string        `json:"ssh_url"`
				CloneURL                  string        `json:"clone_url"`
				SvnURL                    string        `json:"svn_url"`
				Homepage                  interface{}   `json:"homepage"`
				Size                      int           `json:"size"`
				StargazersCount           int           `json:"stargazers_count"`
				WatchersCount             int           `json:"watchers_count"`
				Language                  string        `json:"language"`
				HasIssues                 bool          `json:"has_issues"`
				HasProjects               bool          `json:"has_projects"`
				HasDownloads              bool          `json:"has_downloads"`
				HasWiki                   bool          `json:"has_wiki"`
				HasPages                  bool          `json:"has_pages"`
				ForksCount                int           `json:"forks_count"`
				MirrorURL                 interface{}   `json:"mirror_url"`
				Archived                  bool          `json:"archived"`
				Disabled                  bool          `json:"disabled"`
				OpenIssuesCount           int           `json:"open_issues_count"`
				License                   interface{}   `json:"license"`
				AllowForking              bool          `json:"allow_forking"`
				IsTemplate                bool          `json:"is_template"`
				WebCommitSignoffRequired  bool          `json:"web_commit_signoff_required"`
				Topics                    []interface{} `json:"topics"`
				Visibility                string        `json:"visibility"`
				Forks                     int           `json:"forks"`
				OpenIssues                int           `json:"open_issues"`
				Watchers                  int           `json:"watchers"`
				DefaultBranch             string        `json:"default_branch"`
				AllowSquashMerge          bool          `json:"allow_squash_merge"`
				AllowMergeCommit          bool          `json:"allow_merge_commit"`
				AllowRebaseMerge          bool          `json:"allow_rebase_merge"`
				AllowAutoMerge            bool          `json:"allow_auto_merge"`
				DeleteBranchOnMerge       bool          `json:"delete_branch_on_merge"`
				AllowUpdateBranch         bool          `json:"allow_update_branch"`
				UseSquashPrTitleAsDefault bool          `json:"use_squash_pr_title_as_default"`
				SquashMergeCommitMessage  string        `json:"squash_merge_commit_message"`
				SquashMergeCommitTitle    string        `json:"squash_merge_commit_title"`
				MergeCommitMessage        string        `json:"merge_commit_message"`
				MergeCommitTitle          string        `json:"merge_commit_title"`
			} `json:"repo"`
		} `json:"head"`
		Base struct {
			Label string `json:"label"`
			Ref   string `json:"ref"`
			Sha   string `json:"sha"`
			User  struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Repo struct {
				ID       int    `json:"id"`
				NodeID   string `json:"node_id"`
				Name     string `json:"name"`
				FullName string `json:"full_name"`
				Private  bool   `json:"private"`
				Owner    struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"owner"`
				HTMLURL                   string        `json:"html_url"`
				Description               string        `json:"description"`
				Fork                      bool          `json:"fork"`
				URL                       string        `json:"url"`
				ForksURL                  string        `json:"forks_url"`
				KeysURL                   string        `json:"keys_url"`
				CollaboratorsURL          string        `json:"collaborators_url"`
				TeamsURL                  string        `json:"teams_url"`
				HooksURL                  string        `json:"hooks_url"`
				IssueEventsURL            string        `json:"issue_events_url"`
				EventsURL                 string        `json:"events_url"`
				AssigneesURL              string        `json:"assignees_url"`
				BranchesURL               string        `json:"branches_url"`
				TagsURL                   string        `json:"tags_url"`
				BlobsURL                  string        `json:"blobs_url"`
				GitTagsURL                string        `json:"git_tags_url"`
				GitRefsURL                string        `json:"git_refs_url"`
				TreesURL                  string        `json:"trees_url"`
				StatusesURL               string        `json:"statuses_url"`
				LanguagesURL              string        `json:"languages_url"`
				StargazersURL             string        `json:"stargazers_url"`
				ContributorsURL           string        `json:"contributors_url"`
				SubscribersURL            string        `json:"subscribers_url"`
				SubscriptionURL           string        `json:"subscription_url"`
				CommitsURL                string        `json:"commits_url"`
				GitCommitsURL             string        `json:"git_commits_url"`
				CommentsURL               string        `json:"comments_url"`
				IssueCommentURL           string        `json:"issue_comment_url"`
				ContentsURL               string        `json:"contents_url"`
				CompareURL                string        `json:"compare_url"`
				MergesURL                 string        `json:"merges_url"`
				ArchiveURL                string        `json:"archive_url"`
				DownloadsURL              string        `json:"downloads_url"`
				IssuesURL                 string        `json:"issues_url"`
				PullsURL                  string        `json:"pulls_url"`
				MilestonesURL             string        `json:"milestones_url"`
				NotificationsURL          string        `json:"notifications_url"`
				LabelsURL                 string        `json:"labels_url"`
				ReleasesURL               string        `json:"releases_url"`
				DeploymentsURL            string        `json:"deployments_url"`
				CreatedAt                 interface{}   `json:"created_at"`
				UpdatedAt                 interface{}   `json:"updated_at"`
				PushedAt                  interface{}   `json:"pushed_at"`
				GitURL                    string        `json:"git_url"`
				SSHURL                    string        `json:"ssh_url"`
				CloneURL                  string        `json:"clone_url"`
				SvnURL                    string        `json:"svn_url"`
				Homepage                  interface{}   `json:"homepage"`
				Size                      int           `json:"size"`
				StargazersCount           int           `json:"stargazers_count"`
				WatchersCount             int           `json:"watchers_count"`
				Language                  string        `json:"language"`
				HasIssues                 bool          `json:"has_issues"`
				HasProjects               bool          `json:"has_projects"`
				HasDownloads              bool          `json:"has_downloads"`
				HasWiki                   bool          `json:"has_wiki"`
				HasPages                  bool          `json:"has_pages"`
				ForksCount                int           `json:"forks_count"`
				MirrorURL                 interface{}   `json:"mirror_url"`
				Archived                  bool          `json:"archived"`
				Disabled                  bool          `json:"disabled"`
				OpenIssuesCount           int           `json:"open_issues_count"`
				License                   interface{}   `json:"license"`
				AllowForking              bool          `json:"allow_forking"`
				IsTemplate                bool          `json:"is_template"`
				WebCommitSignoffRequired  bool          `json:"web_commit_signoff_required"`
				Topics                    []interface{} `json:"topics"`
				Visibility                string        `json:"visibility"`
				Forks                     int           `json:"forks"`
				OpenIssues                int           `json:"open_issues"`
				Watchers                  int           `json:"watchers"`
				DefaultBranch             string        `json:"default_branch"`
				AllowSquashMerge          bool          `json:"allow_squash_merge"`
				AllowMergeCommit          bool          `json:"allow_merge_commit"`
				AllowRebaseMerge          bool          `json:"allow_rebase_merge"`
				AllowAutoMerge            bool          `json:"allow_auto_merge"`
				DeleteBranchOnMerge       bool          `json:"delete_branch_on_merge"`
				AllowUpdateBranch         bool          `json:"allow_update_branch"`
				UseSquashPrTitleAsDefault bool          `json:"use_squash_pr_title_as_default"`
				SquashMergeCommitMessage  string        `json:"squash_merge_commit_message"`
				SquashMergeCommitTitle    string        `json:"squash_merge_commit_title"`
				MergeCommitMessage        string        `json:"merge_commit_message"`
				MergeCommitTitle          string        `json:"merge_commit_title"`
			} `json:"repo"`
		} `json:"base"`
		Links struct {
			Self struct {
				Href string `json:"href"`
			} `json:"self"`
			HTML struct {
				Href string `json:"href"`
			} `json:"html"`
			Issue struct {
				Href string `json:"href"`
			} `json:"issue"`
			Comments struct {
				Href string `json:"href"`
			} `json:"comments"`
			ReviewComments struct {
				Href string `json:"href"`
			} `json:"review_comments"`
			ReviewComment struct {
				Href string `json:"href"`
			} `json:"review_comment"`
			Commits struct {
				Href string `json:"href"`
			} `json:"commits"`
			Statuses struct {
				Href string `json:"href"`
			} `json:"statuses"`
		} `json:"_links"`
		AuthorAssociation string      `json:"author_association"`
		AutoMerge         interface{} `json:"auto_merge"`
		ActiveLockReason  interface{} `json:"active_lock_reason"`
		Merged            bool        `json:"merged"`
		Mergeable         interface{} `json:"mergeable"`
		Rebaseable        interface{} `json:"rebaseable"`
		MergeableState    string      `json:"mergeable_state"`
		MergedBy          struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"merged_by"`
		Comments            int  `json:"comments"`
		ReviewComments      int  `json:"review_comments"`
		MaintainerCanModify bool `json:"maintainer_can_modify"`
		Commits             int  `json:"commits"`
		Additions           int  `json:"additions"`
		Deletions           int  `json:"deletions"`
		ChangedFiles        int  `json:"changed_files"`
	} `json:"pull_request"`
	Repository struct {
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		FullName string `json:"full_name"`
		Private  bool   `json:"private"`
		Owner    struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"owner"`
		HTMLURL                  string        `json:"html_url"`
		Description              string        `json:"description"`
		Fork                     bool          `json:"fork"`
		URL                      string        `json:"url"`
		ForksURL                 string        `json:"forks_url"`
		KeysURL                  string        `json:"keys_url"`
		CollaboratorsURL         string        `json:"collaborators_url"`
		TeamsURL                 string        `json:"teams_url"`
		HooksURL                 string        `json:"hooks_url"`
		IssueEventsURL           string        `json:"issue_events_url"`
		EventsURL                string        `json:"events_url"`
		AssigneesURL             string        `json:"assignees_url"`
		BranchesURL              string        `json:"branches_url"`
		TagsURL                  string        `json:"tags_url"`
		BlobsURL                 string        `json:"blobs_url"`
		GitTagsURL               string        `json:"git_tags_url"`
		GitRefsURL               string        `json:"git_refs_url"`
		TreesURL                 string        `json:"trees_url"`
		StatusesURL              string        `json:"statuses_url"`
		LanguagesURL             string        `json:"languages_url"`
		StargazersURL            string        `json:"stargazers_url"`
		ContributorsURL          string        `json:"contributors_url"`
		SubscribersURL           string        `json:"subscribers_url"`
		SubscriptionURL          string        `json:"subscription_url"`
		CommitsURL               string        `json:"commits_url"`
		GitCommitsURL            string        `json:"git_commits_url"`
		CommentsURL              string        `json:"comments_url"`
		IssueCommentURL          string        `json:"issue_comment_url"`
		ContentsURL              string        `json:"contents_url"`
		CompareURL               string        `json:"compare_url"`
		MergesURL                string        `json:"merges_url"`
		ArchiveURL               string        `json:"archive_url"`
		DownloadsURL             string        `json:"downloads_url"`
		IssuesURL                string        `json:"issues_url"`
		PullsURL                 string        `json:"pulls_url"`
		MilestonesURL            string        `json:"milestones_url"`
		NotificationsURL         string        `json:"notifications_url"`
		LabelsURL                string        `json:"labels_url"`
		ReleasesURL              string        `json:"releases_url"`
		DeploymentsURL           string        `json:"deployments_url"`
		CreatedAt                interface{}   `json:"created_at"`
		UpdatedAt                interface{}   `json:"updated_at"`
		PushedAt                 interface{}   `json:"pushed_at"`
		GitURL                   string        `json:"git_url"`
		SSHURL                   string        `json:"ssh_url"`
		CloneURL                 string        `json:"clone_url"`
		SvnURL                   string        `json:"svn_url"`
		Homepage                 interface{}   `json:"homepage"`
		Size                     int           `json:"size"`
		StargazersCount          int           `json:"stargazers_count"`
		WatchersCount            int           `json:"watchers_count"`
		Language                 string        `json:"language"`
		HasIssues                bool          `json:"has_issues"`
		HasProjects              bool          `json:"has_projects"`
		HasDownloads             bool          `json:"has_downloads"`
		HasWiki                  bool          `json:"has_wiki"`
		HasPages                 bool          `json:"has_pages"`
		ForksCount               int           `json:"forks_count"`
		MirrorURL                interface{}   `json:"mirror_url"`
		Archived                 bool          `json:"archived"`
		Disabled                 bool          `json:"disabled"`
		OpenIssuesCount          int           `json:"open_issues_count"`
		License                  interface{}   `json:"license"`
		AllowForking             bool          `json:"allow_forking"`
		IsTemplate               bool          `json:"is_template"`
		WebCommitSignoffRequired bool          `json:"web_commit_signoff_required"`
		Topics                   []interface{} `json:"topics"`
		Visibility               string        `json:"visibility"`
		Forks                    int           `json:"forks"`
		OpenIssues               int           `json:"open_issues"`
		Watchers                 int           `json:"watchers"`
		DefaultBranch            string        `json:"default_branch"`
	} `json:"repository"`
	Sender struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"sender"`
}

type GiteaSchema struct {
	Secret      string `json:"secret"`
	Action      string `json:"action"`
	Ref         string `json:"ref"`
	Before      string `json:"before"`
	After       string `json:"after"`
	CompareURL  string `json:"compare_url"`
	PullRequest struct {
		ID     int    `json:"id"`
		URL    string `json:"url"`
		Number int    `json:"number"`
		User   struct {
			ID        int    `json:"id"`
			Login     string `json:"login"`
			FullName  string `json:"full_name"`
			Email     string `json:"email"`
			AvatarURL string `json:"avatar_url"`
			Language  string `json:"language"`
			IsAdmin   bool   `json:"is_admin"`
			Username  string `json:"username"`
		} `json:"user"`
		Title     string        `json:"title"`
		Body      string        `json:"body"`
		Labels    []interface{} `json:"labels"`
		Milestone interface{}   `json:"milestone"`
		Assignee  interface{}   `json:"assignee"`
		Assignees interface{}   `json:"assignees"`
		State     string        `json:"state"`
		//Comments       string        `json:"comments"`
		HTMLURL        string    `json:"html_url"`
		DiffURL        string    `json:"diff_url"`
		PatchURL       string    `json:"patch_url"`
		Mergeable      bool      `json:"mergeable"`
		Merged         bool      `json:"merged"`
		MergedAt       time.Time `json:"merged_at"`
		MergeCommitSha string    `json:"merge_commit_sha"`
		MergedBy       struct {
			ID        int    `json:"id"`
			Login     string `json:"login"`
			FullName  string `json:"full_name"`
			Email     string `json:"email"`
			AvatarURL string `json:"avatar_url"`
			Language  string `json:"language"`
			IsAdmin   bool   `json:"is_admin"`
			Username  string `json:"username"`
		} `json:"merged_by"`
		Base struct {
			Label  string `json:"label"`
			Ref    string `json:"ref"`
			Sha    string `json:"sha"`
			RepoID int    `json:"repo_id"`
			Repo   struct {
				ID    int `json:"id"`
				Owner struct {
					ID        int    `json:"id"`
					Login     string `json:"login"`
					FullName  string `json:"full_name"`
					Email     string `json:"email"`
					AvatarURL string `json:"avatar_url"`
					Language  string `json:"language"`
					IsAdmin   bool   `json:"is_admin"`
					Username  string `json:"username"`
				} `json:"owner"`
				Name            string      `json:"name"`
				FullName        string      `json:"full_name"`
				Description     string      `json:"description"`
				Empty           bool        `json:"empty"`
				Private         bool        `json:"private"`
				Fork            bool        `json:"fork"`
				Parent          interface{} `json:"parent"`
				Mirror          bool        `json:"mirror"`
				Size            int         `json:"size"`
				HTMLURL         string      `json:"html_url"`
				SSHURL          string      `json:"ssh_url"`
				CloneURL        string      `json:"clone_url"`
				Website         string      `json:"website"`
				StarsCount      int         `json:"stars_count"`
				ForksCount      int         `json:"forks_count"`
				WatchersCount   int         `json:"watchers_count"`
				OpenIssuesCount int         `json:"open_issues_count"`
				DefaultBranch   string      `json:"default_branch"`
				Archived        bool        `json:"archived"`
				CreatedAt       time.Time   `json:"created_at"`
				UpdatedAt       time.Time   `json:"updated_at"`
				Permissions     struct {
					Admin bool `json:"admin"`
					Push  bool `json:"push"`
					Pull  bool `json:"pull"`
				} `json:"permissions"`
			} `json:"repo"`
		} `json:"base"`
		Head struct {
			Label  string `json:"label"`
			Ref    string `json:"ref"`
			Sha    string `json:"sha"`
			RepoID int    `json:"repo_id"`
			Repo   struct {
				ID    int `json:"id"`
				Owner struct {
					ID        int    `json:"id"`
					Login     string `json:"login"`
					FullName  string `json:"full_name"`
					Email     string `json:"email"`
					AvatarURL string `json:"avatar_url"`
					Language  string `json:"language"`
					IsAdmin   bool   `json:"is_admin"`
					Username  string `json:"username"`
				} `json:"owner"`
				Name            string      `json:"name"`
				FullName        string      `json:"full_name"`
				Description     string      `json:"description"`
				Empty           bool        `json:"empty"`
				Private         bool        `json:"private"`
				Fork            bool        `json:"fork"`
				Parent          interface{} `json:"parent"`
				Mirror          bool        `json:"mirror"`
				Size            int         `json:"size"`
				HTMLURL         string      `json:"html_url"`
				SSHURL          string      `json:"ssh_url"`
				CloneURL        string      `json:"clone_url"`
				Website         string      `json:"website"`
				StarsCount      int         `json:"stars_count"`
				ForksCount      int         `json:"forks_count"`
				WatchersCount   int         `json:"watchers_count"`
				OpenIssuesCount int         `json:"open_issues_count"`
				DefaultBranch   string      `json:"default_branch"`
				Archived        bool        `json:"archived"`
				CreatedAt       time.Time   `json:"created_at"`
				UpdatedAt       time.Time   `json:"updated_at"`
				Permissions     struct {
					Admin bool `json:"admin"`
					Push  bool `json:"push"`
					Pull  bool `json:"pull"`
				} `json:"permissions"`
			} `json:"repo"`
		} `json:"head"`
		MergeBase string      `json:"merge_base"`
		DueDate   interface{} `json:"due_date"`
		CreatedAt time.Time   `json:"created_at"`
		UpdatedAt time.Time   `json:"updated_at"`
		ClosedAt  interface{} `json:"closed_at"`
	} `json:"pull_request"`
	Commits []struct {
		ID      string `json:"id"`
		Message string `json:"message"`
		URL     string `json:"url"`
		Author  struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"author"`
		Committer struct {
			Name     string `json:"name"`
			Email    string `json:"email"`
			Username string `json:"username"`
		} `json:"committer"`
		Verification interface{} `json:"verification"`
		Timestamp    time.Time   `json:"timestamp"`
		Added        interface{} `json:"added"`
		Removed      interface{} `json:"removed"`
		Modified     interface{} `json:"modified"`
	} `json:"commits"`
	HeadCommit interface{} `json:"head_commit"`
	Release    struct {
		ID              int       `json:"id"`
		TagName         string    `json:"tag_name"`
		TargetCommitish string    `json:"target_commitish"`
		Name            string    `json:"name"`
		Body            string    `json:"body"`
		URL             string    `json:"url"`
		TarballURL      string    `json:"tarball_url"`
		ZipballURL      string    `json:"zipball_url"`
		Draft           bool      `json:"draft"`
		Prerelease      bool      `json:"prerelease"`
		CreatedAt       time.Time `json:"created_at"`
		PublishedAt     time.Time `json:"published_at"`
		Author          struct {
			ID        int    `json:"id"`
			Login     string `json:"login"`
			FullName  string `json:"full_name"`
			Email     string `json:"email"`
			AvatarURL string `json:"avatar_url"`
			Language  string `json:"language"`
			IsAdmin   bool   `json:"is_admin"`
			Username  string `json:"username"`
		} `json:"author"`
		Assets []interface{} `json:"assets"`
	} `json:"release"`
	Repository struct {
		ID    int `json:"id"`
		Owner struct {
			ID        int    `json:"id"`
			Login     string `json:"login"`
			FullName  string `json:"full_name"`
			Email     string `json:"email"`
			AvatarURL string `json:"avatar_url"`
			Language  string `json:"language"`
			IsAdmin   bool   `json:"is_admin"`
			Username  string `json:"username"`
		} `json:"owner"`
		Name            string      `json:"name"`
		FullName        string      `json:"full_name"`
		Description     string      `json:"description"`
		Empty           bool        `json:"empty"`
		Private         bool        `json:"private"`
		Fork            bool        `json:"fork"`
		Parent          interface{} `json:"parent"`
		Mirror          bool        `json:"mirror"`
		Size            int         `json:"size"`
		HTMLURL         string      `json:"html_url"`
		SSHURL          string      `json:"ssh_url"`
		CloneURL        string      `json:"clone_url"`
		Website         string      `json:"website"`
		StarsCount      int         `json:"stars_count"`
		ForksCount      int         `json:"forks_count"`
		WatchersCount   int         `json:"watchers_count"`
		OpenIssuesCount int         `json:"open_issues_count"`
		DefaultBranch   string      `json:"default_branch"`
		Archived        bool        `json:"archived"`
		CreatedAt       time.Time   `json:"created_at"`
		UpdatedAt       time.Time   `json:"updated_at"`
		Permissions     struct {
			Admin bool `json:"admin"`
			Push  bool `json:"push"`
			Pull  bool `json:"pull"`
		} `json:"permissions"`
	} `json:"repository"`
	Pusher struct {
		ID        int    `json:"id"`
		Login     string `json:"login"`
		FullName  string `json:"full_name"`
		Email     string `json:"email"`
		AvatarURL string `json:"avatar_url"`
		Language  string `json:"language"`
		IsAdmin   bool   `json:"is_admin"`
		Username  string `json:"username"`
	} `json:"pusher"`
	Sender struct {
		ID        int    `json:"id"`
		Login     string `json:"login"`
		FullName  string `json:"full_name"`
		Email     string `json:"email"`
		AvatarURL string `json:"avatar_url"`
		Language  string `json:"language"`
		IsAdmin   bool   `json:"is_admin"`
		Username  string `json:"username"`
	} `json:"sender"`
}

type EventListenerSchema struct {
	Repository struct {
		URL  string `json:"url"`
		Name string `json:"name"`
		Ref  string `json:"ref"`
		Hash string `json:"hash"`
		Tag  string `json:"tag"`
	} `json:"repository"`
	User    string `json:"user"`
	Email   string `json:"email"`
	Message string `json:"message"`
	Sonar   struct {
		URL string `json:"url"`
	} `json:"sonar"`
}
